import type { Playlist, PlaylistTrack } from "./types";

const LIKES_TRACKS: PlaylistTrack[] = [
  { id: "likes-01", title: "undressed", artist: "sombr", youtubeId: "z0wT6CrEGYg" },
  { id: "likes-02", title: "12 to 12", artist: "sombr", youtubeId: "cZgUiR31m-Y" },
  { id: "likes-03", title: "Basic Being Basic", artist: "Djo", youtubeId: "3AYJJQEMHwo" },
  { id: "likes-04", title: "Don't Go Insane", artist: "DPR IAN", youtubeId: "nZ5SfoLB5yA" },
  { id: "likes-05", title: "Peanut Butter & Tears", artist: "DPR IAN", youtubeId: "pCBgcBXxCsI" },
  { id: "likes-06", title: "better late than never", artist: "almost monday", youtubeId: "7bd-XjhsGlE" },
  { id: "likes-07", title: "enjoy the ride", artist: "almost monday", youtubeId: "nNYOk4y8RsA" },
  { id: "likes-08", title: "California", artist: "beabadoobee", youtubeId: "JGIheyWlEkg" },
  { id: "likes-09", title: "Cologne", artist: "beabadoobee", youtubeId: "aalRn01lMmg" },
  { id: "likes-10", title: "Loser", artist: "Tame Impala", youtubeId: "s3a4OQR-10M" },
  { id: "likes-11", title: "thank you i guess", artist: "Forrest Nolan", youtubeId: "-9ZmP35jWFQ" },
  { id: "likes-12", title: "of everyone in the world...", artist: "Forrest Nolan", youtubeId: "VJ2hjtkAzYc" },
  { id: "likes-13", title: "What You Know", artist: "Two Door Cinema Club", youtubeId: "YXwYJyrKK5A" },
  { id: "likes-14", title: "Knee Socks", artist: "Arctic Monkeys", youtubeId: "lyO-Sveg6a8" },
  { id: "likes-15", title: "Why'd You Only Call Me When You're High?", artist: "Arctic Monkeys", youtubeId: "6366dxFf-Os" },
  { id: "likes-16", title: "Breathe", artist: "Malcolm Todd", youtubeId: "g1uEqR5eFMo" },
  { id: "likes-17", title: "Concrete", artist: "Malcolm Todd", youtubeId: "nQYUnkJeBok" },
  { id: "likes-18", title: "Hotel Room", artist: "Ax and the Hatchetmen", youtubeId: "9Z1k8thLiNE" },
  { id: "likes-19", title: "4EVER", artist: "Clairo", youtubeId: "tlGUom_AV4o" },
  { id: "likes-20", title: "Add Up My Love", artist: "Clairo", youtubeId: "hLrGvkul3_k" },
  { id: "likes-21", title: "White Keys", artist: "Dominic Fike", youtubeId: "Cz200209hOs" },
  { id: "likes-22", title: "Frisky", artist: "Dominic Fike", youtubeId: "-mMdHkKxaZA" },
  { id: "likes-23", title: "All I Ever Asked", artist: "Rachel Chinouriri", youtubeId: "2QXSnc_9OuU" },
  { id: "likes-24", title: "Stargazing", artist: "The Neighbourhood", youtubeId: "8giBPUpzKRw" },
  { id: "likes-25", title: "Planet", artist: "The Neighbourhood", youtubeId: "v-Qfy1Zk6R8" },
  { id: "likes-26", title: "bad idea!", artist: "girl in red", youtubeId: "Xo8QvY0jOOE" },
  { id: "likes-27", title: "I'll Call You Mine", artist: "girl in red", youtubeId: "vQkRDWI4Tqo" },
  { id: "likes-28", title: "Farewell", artist: "marQ", youtubeId: "9q0zannt7dY" },
  { id: "likes-29", title: "Honeypie", artist: "JAWNY", youtubeId: "Wgw6tJ8yz9M" },
  { id: "likes-30", title: "Love Me Not (feat. Rex Orange County)", artist: "Ravyn Lenae", youtubeId: "kugYXtEpMeM" },
  { id: "likes-31", title: "Tek It", artist: "Cafuné", youtubeId: "7RWbq-lbBlk" },
  { id: "likes-32", title: "Killshot", artist: "Magdalena Bay", youtubeId: "lhfs1CzzUPM" },
  { id: "likes-33", title: "Vending Machine", artist: "Valley", youtubeId: "o9b4v2Vc3FM" },
];

const JPOP_TRACKS: PlaylistTrack[] = [
  { id: "jpop-01", title: "Lemon", artist: "Kenshi Yonezu", youtubeId: "SX_ViT4Ra7k" },
  { id: "jpop-02", title: "Pretender", artist: "Official HIGE DANDism", youtubeId: "TQ8WlA2GXbk" },
  { id: "jpop-03", title: "白日 (Hakujitsu)", artist: "King Gnu", youtubeId: "ony539T074w" },
  { id: "jpop-04", title: "廻廻奇譚 (Kaikai Kitan)", artist: "Eve", youtubeId: "1tk1pqwrOys" },
  { id: "jpop-05", title: "怪物 (Monster)", artist: "YOASOBI", youtubeId: "dy90tA3TT1c" },
  { id: "jpop-06", title: "Marigold", artist: "Aimyon", youtubeId: "0xSiBpUdW4E" },
  { id: "jpop-07", title: "KICKBACK", artist: "Kenshi Yonezu", youtubeId: "M2cckDmNLMI" },
  { id: "jpop-08", title: "Homura", artist: "LiSA", youtubeId: "4DxL6IKmXx4" },
  { id: "jpop-09", title: "NIGHT DANCER", artist: "imase", youtubeId: "kagoEGKHZvU" },
  { id: "jpop-10", title: "Zenzenzense", artist: "RADWIMPS", youtubeId: "PDSkFeMVNFs" },
  { id: "jpop-11", title: "Suiheisen", artist: "back number", youtubeId: "iqEr3P78fz8" },
  { id: "jpop-12", title: "Zankyosanka", artist: "Aimer", youtubeId: "tLQLa6lM3Us" },
  { id: "jpop-13", title: "Racing into the Night (夜に駆ける)", artist: "YOASOBI", youtubeId: "x8VYWazR5mE" },
  { id: "jpop-14", title: "Shinunoga E-Wa", artist: "Fujii Kaze", youtubeId: "dawrQnvwMTY" },
  { id: "jpop-15", title: "Koi", artist: "Gen Hoshino", youtubeId: "jhOVibLEDhA" },
  { id: "jpop-16", title: "U.S.A.", artist: "DA PUMP", youtubeId: "sr--GVIoluU" },
  { id: "jpop-17", title: "Just a Sunny Day for You", artist: "Yorushika", youtubeId: "-VKIqrvVOpo" },
  { id: "jpop-18", title: "Show (唱)", artist: "Ado", youtubeId: "pgXpM4l_MwI" },
  { id: "jpop-19", title: "Shintakarajima", artist: "Sakanaction", youtubeId: "LIlZCmETvsY" },
  { id: "jpop-20", title: "Overdose", artist: "natori", youtubeId: "H08YWE4CIFQ" },
  { id: "jpop-21", title: "Habit", artist: "SEKAI NO OWARI", youtubeId: "8OZDgBmehbA" },
  { id: "jpop-22", title: "Lilac (ライラック)", artist: "Mrs. GREEN APPLE", youtubeId: "QjrkrVmC-8M" },
  { id: "jpop-23", title: "Gunjou (群青)", artist: "YOASOBI", youtubeId: "Y4nEEZwckuU" },
  { id: "jpop-24", title: "Dry Flower", artist: "Yuuri", youtubeId: "kzZ6KXDM1RI" },
  { id: "jpop-25", title: "Machigai Sagashi", artist: "Suda Masaki", youtubeId: "7940nuwCEYA" },
  { id: "jpop-26", title: "Kanade", artist: "Sukima Switch", youtubeId: "J5Z7tIq7bco" },
  { id: "jpop-27", title: "PONPONPON", artist: "Kyary Pamyu Pamyu", youtubeId: "yzC4hFK5P3g" },
  { id: "jpop-28", title: "Kaijuu no Hanauta", artist: "Vaundy", youtubeId: "UM9XNpgrqVk" },
  { id: "jpop-29", title: "SPECIALZ", artist: "King Gnu", youtubeId: "fhzKLBZJC3w" },
  { id: "jpop-30", title: "New Genesis (新時代)", artist: "Ado", youtubeId: "1FliVTcX8bQ" },
  { id: "jpop-31", title: "Flamingo", artist: "Kenshi Yonezu", youtubeId: "Uh6dkL1M9DM" },
  { id: "jpop-32", title: "Ai wo Komete Hanataba wo", artist: "Superfly", youtubeId: "gU5oN0KVofU" },
  { id: "jpop-33", title: "R.Y.U.S.E.I.", artist: "Sandaime J Soul Brothers", youtubeId: "4-Gw0TAM6-Q" },
  { id: "jpop-34", title: "Kousui (香水)", artist: "Eito", youtubeId: "9MjAJSoaoSo" },
  { id: "jpop-35", title: "Akuma no Ko", artist: "Ai Higuchi", youtubeId: "N4F3bjlL_H4" },
];

const KPOP_TRACKS: PlaylistTrack[] = [
  { id: "kpop-01", title: "SUGAR HONEY ICE TEA", artist: "BABYMONSTER", youtubeId: "naoGk-Zjc1s" },
  { id: "kpop-02", title: "LEMONADE", artist: "aespa", youtubeId: "83C3TZ4Zm_o" },
  { id: "kpop-03", title: "It's Me", artist: "ILLIT", youtubeId: "bMhDJ0S0OBA" },
  { id: "kpop-04", title: "CELEBRATION", artist: "LE SSERAFIM", youtubeId: "a2grcJdfXmY" },
  { id: "kpop-05", title: "Love Me More", artist: "Apink", youtubeId: "y2os26sMjOg" },
  { id: "kpop-06", title: "THIS IS FOR", artist: "TWICE", youtubeId: "eHHQaoEW30Q" },
  { id: "kpop-07", title: "2.0", artist: "BTS", youtubeId: "_gyultVTesk" },
  { id: "kpop-08", title: "LOOK AT ME", artist: "ALLDAY PROJECT", youtubeId: "9nOrPNxjvck" },
  { id: "kpop-09", title: "REDRED", artist: "CORTIS", youtubeId: "U6BDbXIah-Y" },
  { id: "kpop-10", title: "Crow", artist: "(G)I-DLE", youtubeId: "bUMLC9lCgHo" },
  { id: "kpop-11", title: "EYES CLOSED", artist: "JISOO X ZAYN", youtubeId: "EN1tMeXQii0" },
  { id: "kpop-12", title: "Hollow", artist: "Stray Kids", youtubeId: "F4qFzuCA9Po" },
  { id: "kpop-13", title: "Do your dance", artist: "RIIZE", youtubeId: "HDGCTtuW-Yo" },
  { id: "kpop-14", title: "JUMP", artist: "BLACKPINK", youtubeId: "CgCVZdcKcqY" },
  { id: "kpop-15", title: "PINKY UP", artist: "KATSEYE", youtubeId: "7F1ET2XHQfk" },
  { id: "kpop-16", title: "Golden", artist: "HUNTR/X (KPop Demon Hunters)", youtubeId: "yebNIHKAC4A" },
  { id: "kpop-17", title: "Paradise of Rumors", artist: "AKMU", youtubeId: "D54StAZFUrc" },
  { id: "kpop-18", title: "Spinnin' On It", artist: "NMIXX", youtubeId: "RblIsNFR1j4" },
  { id: "kpop-19", title: "BANG BANG", artist: "IVE", youtubeId: "9qkpcLK422o" },
  { id: "kpop-20", title: "GO", artist: "BLACKPINK", youtubeId: "2GJfWMYCWY0" },
  { id: "kpop-21", title: "Adrenaline", artist: "ATEEZ", youtubeId: "vqkfEUqjl6Y" },
  { id: "kpop-22", title: "Pookie", artist: "FIFTY FIFTY", youtubeId: "1ZX1vEDTfY4" },
  { id: "kpop-23", title: "UNIQUE", artist: "P1Harmony", youtubeId: "m18dRRu9-V4" },
  { id: "kpop-24", title: "Dirty Work", artist: "aespa", youtubeId: "M2WTUoy4y6E" },
  { id: "kpop-25", title: "STYLE", artist: "Hearts2Hearts", youtubeId: "n7kFRxFIPrI" },
  { id: "kpop-26", title: "Gabriela", artist: "KATSEYE", youtubeId: "CjnB56tSCQI" },
  { id: "kpop-27", title: "Hollywood Action", artist: "BOYNEXTDOOR", youtubeId: "yAtew9dZX_E" },
  { id: "kpop-28", title: "MONA LISA", artist: "j-hope", youtubeId: "ECqGCH1TfLY" },
  { id: "kpop-29", title: "청바지 (Cheongbaji)", artist: "BSS (Seventeen)", youtubeId: "Mt9SBZam4X4" },
  { id: "kpop-30", title: "Good Goodbye", artist: "HWASA", youtubeId: "Qe8fa4b5xNU" },
  { id: "kpop-31", title: "like JENNIE", artist: "JENNIE", youtubeId: "JSFG-IE8n_c" },
  { id: "kpop-32", title: "APT.", artist: "ROSÉ & Bruno Mars", youtubeId: "ekr2nIex040" },
  { id: "kpop-33", title: "Supernatural", artist: "NewJeans", youtubeId: "ZncbtRo7RXs" },
  { id: "kpop-34", title: "Seven (feat. Latto)", artist: "Jung Kook", youtubeId: "QU9c0053UAU" },
  { id: "kpop-35", title: "Bite Me", artist: "ENHYPEN", youtubeId: "wXFLzODIdUI" },
];

const PPOP_TRACKS: PlaylistTrack[] = [
  { id: "ppop-01", title: "Sinta", artist: "Rob Deniel", youtubeId: "V5Ncu4eLJFA" },
  { id: "ppop-02", title: "Miss Miss", artist: "Rob Deniel", youtubeId: "B2bnLUce6wI" },
  { id: "ppop-03", title: "Simoy", artist: "Rob Deniel", youtubeId: "XQl2rewiowE" },
  { id: "ppop-04", title: "RomCom", artist: "Rob Deniel", youtubeId: "wUYAUP-uPjQ" },
  { id: "ppop-05", title: "Nandito Ako", artist: "Rob Deniel", youtubeId: "TRx6yi_kVxI" },
  { id: "ppop-06", title: "Ang Pag-ibig", artist: "Rob Deniel", youtubeId: "ozvIU6EgZwk" },
  { id: "ppop-07", title: "Tibok", artist: "Earl Agustin", youtubeId: "pSAtptOY7dI" },
  { id: "ppop-08", title: "Dalangin", artist: "Earl Agustin", youtubeId: "Yx-qdY6i5qI" },
  { id: "ppop-09", title: "Aya", artist: "Earl Agustin", youtubeId: "nODwI0ogvuo" },
  { id: "ppop-10", title: "Dito Sa'kin", artist: "Earl Agustin", youtubeId: "4uN_HQZjiB0" },
  { id: "ppop-11", title: "Mundo", artist: "IV OF SPADES", youtubeId: "omFa4Yk9Fmg" },
  { id: "ppop-12", title: "Kabisado", artist: "IV OF SPADES", youtubeId: "uyC8mS5MHkk" },
  { id: "ppop-13", title: "Come Inside Of My Heart", artist: "IV OF SPADES", youtubeId: "HxwokFPIguU" },
  { id: "ppop-14", title: "Aura", artist: "IV OF SPADES", youtubeId: "5yHaatld7rY" },
  { id: "ppop-15", title: "Pasilyo", artist: "SunKissed Lola", youtubeId: "XToA-1dZYWA" },
  { id: "ppop-16", title: "Paki Sabi", artist: "SunKissed Lola", youtubeId: "6hOFULDlu6A" },
  { id: "ppop-17", title: "Pag-Ibig ay Kanibalismo II", artist: "fitterkarma", youtubeId: "nw0tZFyExtY" },
  { id: "ppop-18", title: "Mahika", artist: "Adie, Janine Berdin", youtubeId: "9tLglpFAyIg" },
  { id: "ppop-19", title: "Leonora", artist: "Sugarcane", youtubeId: "hOf7m31ZvgQ" },
  { id: "ppop-20", title: "Pagsamo", artist: "Arthur Nery", youtubeId: "Hx4-GMWWb7Q" },
  { id: "ppop-21", title: "Isa Lang", artist: "Arthur Nery", youtubeId: "6m-ZuVb1tK4" },
  { id: "ppop-22", title: "Palaisipan (feat. Arthur Nery)", artist: "Loonie", youtubeId: "DLPmi48O51s" },
  { id: "ppop-23", title: "Raining In Manila", artist: "Lola Amour", youtubeId: "dglBgJSMr-E" },
  { id: "ppop-24", title: "Fallen", artist: "Lola Amour", youtubeId: "S3wytd6ZbXc" },
  { id: "ppop-25", title: "dahan-dahan", artist: "Lola Amour", youtubeId: "lHiJLqQ59P8" },
  { id: "ppop-26", title: "Ikot", artist: "Over October", youtubeId: "8yvWcZ8BtrQ" },
  { id: "ppop-27", title: "Panalangin", artist: "APO Hiking Society", youtubeId: "2KBffqrAAc4" },
  { id: "ppop-28", title: "Tadhana", artist: "Up Dharma Down", youtubeId: "TjEbuWP3hjg" },
  { id: "ppop-29", title: "Unti-Unti", artist: "Up Dharma Down", youtubeId: "vw4MWvpJsqI" },
  { id: "ppop-30", title: "Oo", artist: "Up Dharma Down", youtubeId: "0gMG_EPwiIQ" },
  { id: "ppop-31", title: "Burnout", artist: "Sugarfree", youtubeId: "Um-B-dd94jg" },
  { id: "ppop-32", title: "Tingin", artist: "Cup of Joe, Janine Teñoso", youtubeId: "aJakSXHZROo" },
  { id: "ppop-33", title: "Estranghero", artist: "Cup of Joe", youtubeId: "vBG5XMUyl70" },
  { id: "ppop-34", title: "LASIK", artist: "HEY JUNE!", youtubeId: "bb_LerK3ZXA" },
  { id: "ppop-35", title: "Happy Ending", artist: "Rob Deniel", youtubeId: "d-ic7ySu9dQ" },
  { id: "ppop-36", title: "Ikaw Lang", artist: "NOBITA", youtubeId: "rxXsdj7EBm4" },
];

export const PLAYLISTS: Playlist[] = [
  { id: "likes", label: "likes", emoji: "🍰", tracks: LIKES_TRACKS },
  { id: "jpop", label: "jpop", emoji: "🎌", tracks: JPOP_TRACKS },
  { id: "kpop", label: "kpop", emoji: "🇰🇷", tracks: KPOP_TRACKS },
  { id: "ppop", label: "ppop", emoji: "🇵🇭", tracks: PPOP_TRACKS },
];
